### ISSUE TITLE
ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by Pillow-Fan** [riklus/ilcorsaronero-stremio-addon#2]
Dopo aver installato node.js e fatto partire il comando specificato nella cartella dove si trovava lo script, il terminale restituisce l'errore:
[ERR_MODULE_NOT_FOUND]: Cannot find package 'stremio-addon-sdk' imported from C:\Users\*\Desktop\ilcorsaronero-stremio-addon-main\addon.js
Ho anche provato a installare lo stremio-addon-sdk ma l'errore persiste. Come posso rimediare?

**Comment by riklus** [comment]
Prova a fare:

```
npm install
```

Nella cartella della repo.

**Comment by Pillow-Fan** [comment]
Ho fatto partire il comando e il problema con stremio-addon-sdk è scomparso. Adesso però lo stesso errore avviene con "imdb-api"
